name: CI
on:
  pull_request:
  push:
    branches: [master, main]
    tags: ['*']
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10' # LTS
          - '1.11'
          - '1'    # latest stable 1.x
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - os: macos-latest
            version: '1.11'
            arch: aarch64
          - os: windows-latest
            version: '1.11'
            arch: x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_NUM_THREADS: 4
        with:
          coverage: false
